# Generated by Django 3.2.15 on 2022-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='id',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
