# Generated by Django 3.2.15 on 2022-10-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20221001_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=64)),
                ('url_image', models.CharField(default='https://image.shutterstock.com/image-vector/image-not-found-grayscale-photo-260nw-1737334631.jpg', max_length=200)),
                ('starting_bid', models.FloatField()),
            ],
        ),
    ]
