# Generated by Django 3.2.15 on 2022-09-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bids_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='url_image',
            field=models.CharField(default='https://image.shutterstock.com/image-vector/image-not-found-grayscale-photo-260nw-1737334631.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
