# Generated by Django 3.2.15 on 2022-10-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlistingpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionListing',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlistingpage'),
        ),
    ]
