# Generated by Django 3.2.15 on 2022-10-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20221005_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_date',
            field=models.CharField(max_length=100),
        ),
    ]
