# Generated by Django 3.2.15 on 2022-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistingpage',
            name='seller',
            field=models.CharField(default='Not Stated', max_length=64),
        ),
        migrations.AddField(
            model_name='comments',
            name='auction_id',
            field=models.IntegerField(default=0),
        ),
    ]
