# Generated by Django 3.2.15 on 2022-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20221007_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
