# Generated by Django 3.2.15 on 2022-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bids_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistingpage',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='auction_id',
            field=models.IntegerField(default=0),
        ),
    ]
